<?php

//Help menu hook
function farm_area_combined_help($path, $arg){
	switch($path){
		case "admin/help#farm_area_combined":
			return t("Displays the area in alternative units. If you are using metric, it will display the imperial measurement, and the other way around.");
			break;
	}
}


//Settings menu hook
function farm_area_combined_menu(){
	$items = array();
    $items['admin/config/farm/area_combined'] = array(
        'title' => t('Displayed Area Units'),
        'description' => t('Configures the combined area module - which shows both metric and imperial units for areas'),
        'page arguments' => array('farm_area_combined_settings_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE
    );

	return $items;
}
//Settings form
function farm_area_combined_settings_form($form, &$form_state){
	    $form ['farm_area_combined_settings'] = array(
            '#type' => 'checkbox',
            '#title' => t('Enable combined units?'),
            '#description' => t('Enable combined units in the field map popups'),
            '#default_value' => variable_get('farm_area_combined_settings', 0)
	    );
	return system_settings_form($form);
	
}


function farm_area_combined_farm_area_details($id){
    $output = array();
    //Check if the settings are enabled
    $setting_enabled = variable_get('farm_area_combined_settings',0);


    if ($setting_enabled === 1){    //If enabled...

        $area_meters = farm_area_calculate_area($id,FALSE);
        if (!empty($area_meters)){      //If we have a polygon... Otherwise it might be a point or line...


            //Take the meters and see if they're big or small...
            $size = farm_area_relative_size($area_meters);

            //Get the units for that size
            $units = farm_area_default_units('area',$size);

            switch ($units){
                case 'hectares':
                    //Site is metric, so give imperial (big area)
                    $converted_units = 'acres';
                    $output_area = $area_meters / 4046.856;
                    $unit_style = 'Imperial';
                    break;

                case 'square meters':
                    //Site is metric, so give imperial (small area)
                    $converted_units = 'square feet';
                    $output_area = $area_meters * 10.764;
                    $unit_style = 'Imperial';
                    break;

                case 'acres':
                    //Site is imperial, so give metric (big area)
                    $converted_units = 'ha';
                    $output_area = $area_meters / 10000;
                    $unit_style = 'Metric';
                    break;

                case 'square feet':
                    //Site is imperial, so give metric (small area)
                    $converted_units = 'square meters';
                    $output_area = $area_meters;
                    $unit_style = 'Metric';
                    break;

                default:
                    //other... Give it in acres
                    $converted_units = 'acres';
                    $output_area = $area_meters / 4046.856;
                    $unit_style = 'Imperial';
                    break;
            }

            //Round it to 2 units of precision
            $output_area = round($output_area,2);

            //And display!
            $output['details']= array(
                '#type' => 'markup',
                '#markup' => '<small><p>'. t($unit_style) . t(' units:  ').$output_area. ' '. $converted_units . '</p></small>',
                '#weight' => -98,
            );
        }
    }

    return $output;
}